baseurl: /starter
permalink: pretty
markdown: rdiscount


prose:
  rooturl: '_posts'
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "Strava session id"
        field:
          element: "text"
          label: "ID goes here.."
          value: ""
      - name: "Duration"
        field:
          element: "text"
          label: "hh:mm:ss"
          value: ""
      - name: "Distance"
        field:
          element: "text"
          label: "km"
          value: ""
      - name: "Descent"
        field:
          element: "text"
          label: "m"
          value: ""
      - name: "Ascent"
        field:
          element: "text"
          label: "m"
          value: ""
      - name: "Avg speed"
        field:
          element: "text"
          label: "km/h"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Running"
              value: "running"
            - name: "Cycling"
              value: "cycling"
            - name: "recovery"
              value: "recovery"
            - name: "race"
              value: "race"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
